services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.workers.celery_app.celery_app worker --loglevel=INFO
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.workers.celery_app.celery_app beat --loglevel=INFO
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: qalam
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres-data:
